AWSTemplateFormatVersion: '2010-09-09'
Parameters:

  DestinationAccount:
    Type: String

  DestinationPrefix:
    Type: String
    Default: workshop

  StackPrefix:
    Type: String
    Default: stacklet

  IAMRegion:
    Type: String
    Default: us-east-1

Conditions:
  "CreateIAMResource": !Equals
    - !Ref AWS::Region
    - !Ref IAMRegion
  "TargetSelfAgg": !Equals
    - !Ref AWS::AccountId
    - !Ref DestinationAccount

Resources:
  EventForwardRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub "${StackPrefix}-event-forward"
      Description: !Sub "${StackPrefix} Event Forwarding"
      EventPattern:
        detail:
          readOnly: [false]
          managementEvent: [true]
          errorCode:
            - exists: false
          eventSource:
            [
              {
                "anything-but":
                  [
                    "sts.amazonaws.com"
                  ]
              }
            ]
        detail-type:
          - "AWS API Call via CloudTrail"
      State: "ENABLED"
      Targets:
        Fn::If:
          - TargetSelfAgg
          -
            - Id: NetForwardEvents
              Arn: !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:${StackPrefix}-relay"
          -
            - Id: NetForwardEvents
              Arn: !Sub "arn:aws:events:${AWS::Region}:${DestinationAccount}:event-bus/default"
              RoleArn: !Sub "arn:aws:iam::${AWS::AccountId}:role/${StackPrefix}-forward"

  NetDescribeRole:
    Type: "AWS::IAM::Role"
    Condition: CreateIAMResource
    Properties:
      RoleName: !Sub "${StackPrefix}-discover"
      Description: !Sub "${StackPrefix} Read-Only Resource Collection"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: "sts:AssumeRole"
            Principal:
              AWS: !Sub "arn:aws:iam::${DestinationAccount}:role/${DestinationPrefix}-collector"
      Path: /
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/ReadOnlyAccess"

  NetEventForwardRole:
    Type: "AWS::IAM::Role"
    Condition: CreateIAMResource
    Properties:
      RoleName: !Sub "${StackPrefix}-forward"
      Description: !Sub "${StackPrefix} Event Forwarding"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - events.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Path: /
      Policies:
        - PolicyName: PutEventsNetForward
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: "events:PutEvents"
                Resource: !Sub "arn:aws:events:*:${DestinationAccount}:event-bus/default"

  DescribePolicy:
    Type: "AWS::IAM::Policy"
    Condition: CreateIAMResource
    Properties:
      Roles:
        - !Ref NetDescribeRole
      PolicyName: !Sub "${StackPrefix}-describe-augments"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "support:Describe*"
              - "appflow:List*"
              - "appflow:Describe*"
            Resource: "*"

  ExecutionRole:
    Type: "AWS::IAM::Role"
    Condition: CreateIAMResource
    Properties:
      RoleName: !Sub "${StackPrefix}-execution"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: "sts:AssumeRole"
            Principal:
              AWS: !Sub "arn:aws:iam::${DestinationAccount}:role/${DestinationPrefix}-stacklet-execution"
      Path: /
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/ReadOnlyAccess"
      Policies:
        - PolicyName: AllowSQS
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "sqs:SendMessage"
                Resource: !Sub "arn:aws:sqs:*:${DestinationAccount}:*"
        - PolicyName: AllowKMS
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: ["kms:Decrypt", "kms:GenerateDataKey"]
                Resource: !Sub "arn:aws:kms:*:${DestinationAccount}:*"

Outputs:
  NetDescribeRoleArn:
    Description: "Stacklet Collector Role Arn"
    Value: !GetAtt NetDescribeRole.Arn
    Condition: CreateIAMResource


  NetEventForwardRoleArn:
    Description: "Stacklet Forwarder Role Arn"
    Value: !GetAtt NetEventForwardRole.Arn
    Condition: CreateIAMResource

  ExecutionRoleArn:
    Description: "Stacklet Execution Role Arn"
    Value: !GetAtt ExecutionRole.Arn
    Condition: CreateIAMResource
